### ISSUE TITLE
create table not found please check sql syntax

### ISSUE THREAD

**Issue by CXeon** [Shonminh/go-orm-code-helper#7]
使用的workbench 8 导出的sql,用插件导出报create table not found please check sql syntax

**Comment by Shonminh** [comment]
需要提供更详细的场景， 看下有无使用了mysql的关键字，以及sql的语法。

**Comment by Shonminh** [comment]
近期做了refactor，会发一个新版，相关功能正在开发中，感谢关注:)

**Comment by Shonminh** [comment]
请使用https://plugins.jetbrains.com/plugin/13476-go-orm-code-helper 最新版

**Comment by CXeon** [comment]
> 请使用https://plugins.jetbrains.com/plugin/13476-go-orm-code-helper 最新版
反馈好及时啊，好的好的
